### ISSUE TITLE
powerline.kak: Warning, trying to load non-existing module 'git'

### ISSUE THREAD

**Issue by basbebe** [jdugan6240/powerline.kak#8] opened 2020-11-26 14:19 UTC
## Problem description

I'm getting these lines in the debu buffer if I'm opening files in a git repo: 
```
powerline.kak: Warning, trying to load non-existing module 'git'
powerline.kak: Warning, trying to load non-existing module 'git'
powerline.kak: Warning, trying to load non-existing module 'git'
powerline.kak: Warning, trying to load non-existing module 'git'

```

## Steps to reproduce

1. go to git repo
2. open random file

## What should happen

No debug messages

## What happens instead

debug messages

## Environment information
Kakoune version: 2020.09.01
OS version: MacOS 10.15.7
`sh` executable version: <!-- result of `yourshell --version` fish, version 3.1.2 / GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

**Comment by jdugan6240** [comment] 2020-11-27 19:04
Sorry for the delay in replying - I had family over for thanksgiving and didn't have time to check this.

There's a couple of things that your report seems to be telling me.

First off, how are you loading the plugin? Are you using a plugin manager such as `plug.kak`, or are you loading the plugin manually with source calls? If the latter is the case, then you need to source each module that is used manually. By default, these modules are  git, bufname, line_column, mode_info, filetype, client, session, and position. The error messages you are getting seem to be indicating that you haven't sourced the git module.

Also, it's not clear based on your environment information whether the `sh` executable is a link to `bash` or `fish`. If the latter, then that's a problem, since Kakoune plugins tend to rely on POSIX shell constructs to work, which the `fish` shell doesn't support.

Would you mind posting your kakrc, and which shell the `sh` executable calls?

**Comment by basbebe** [comment] 2020-11-27 20:45
No reaason to apologize!

Sorry for the imcomplete report – here's my current `kakrc`

```
# Plugins

# source custom plugins
source "~/git/pandoc.kak/rc/pandoc.kak"

# source plug.kak script
source "%val{config}/plugins/plug.kak/rc/plug.kak"

# call plug.kak with `plug' command
plug "andreyorst/plug.kak" noload config %{
        # configure plug.kak here
        }
        
plug "ul/kak-lsp" do %{
    cargo build --release --locked
    cargo install --force --path .
} config %{

    # uncomment to enable debugging
    # eval %sh{echo ${kak_opt_lsp_cmd} >> /tmp/kak-lsp.log}
    # set global lsp_cmd "kak-lsp -s %val{session} -vvv --log /tmp/kak-lsp.log"

    # this is not necessary; the `lsp-enable-window` will take care of it
    # eval %sh{${kak_opt_lsp_cmd} --kakoune -s $kak_session}

    set global lsp_diagnostic_line_error_sign '║'
    set global lsp_diagnostic_line_warning_sign '┊'

    define-command ne -docstring 'go to next error/warning from lsp' %{ lsp-find-error --include-warnings }
    define-command pe -docstring 'go to previous error/warning from lsp' %{ lsp-find-error --previous --include-warnings }
    define-command ee -docstring 'go to current error/warning from lsp' %{ lsp-find-error --include-warnings; lsp-find-error --previous --include-warnings }

    define-command lsp-restart -docstring 'restart lsp server' %{ lsp-stop; lsp-start }
    hook global WinSetOption filetype=(c|cpp|cc|rust|javascript|typescript) %{
        set-option window lsp_auto_highlight_references true
        set-option window lsp_hover_anchor false
        lsp-auto-hover-enable
        echo -debug "Enabling LSP for filtetype %opt{filetype}"
        lsp-enable-window
    }

    hook global WinSetOption filetype=(rust) %{
        set window lsp_server_configuration rust.clippy_preference="on"
    }

    hook global WinSetOption filetype=rust %{
        hook window BufWritePre .* %{
            evaluate-commands %sh{
                test -f rustfmt.toml && printf lsp-formatting-sync
            }
        }
    }

    hook global KakEnd .* lsp-exit
}

plug "jdugan6240/powerline.kak" defer powerline %{
    # set-option global powerline_format 'git bufname filetype mode_info line_column position'
    # powerline-toggle line_column off
    powerline-separator triangle
    powerline-theme gruvbox
} config %{
    powerline-start
}
plug "caksoylar/kakoune-smooth-scroll" config %{
     hook global WinCreate .* %{ hook -once window WinDisplay .* smooth-scroll-enable }
}
plug "alexherbo2/prelude.kak"
plug "alexherbo2/connect.kak" %{
    require-module connect
    require-module connect-nnn
}
plug 'alexherbo2/palette.kak'
plug 'occivink/kakoune-sudo-write '
plug 'evanrelf/number-toggle.kak' %{
    set-option global number_toggle_params -hlcursor
}
plug 'alexherbo2/surround.kak' %{
    require-module surround
    ## Quoting
    map -docstring 'Surround' global normal q ': enter-user-mode surround<ret>'
    map -docstring 'Surround insert' global normal Q ': surround-enter-insert-mode<ret>'

    ## Move macros to ^
    map -docstring 'Play macro' global normal ^ q
    map -docstring 'Record macro' global normal <a-^> Q
}
plug 'alexherbo2/auto-pairs.kak' %{
    require-module auto-pairs
    hook global WinCreate .* %{ auto-pairs-enable }
}
plug 'laelath/kakoune-show-matching-insert'
plug 'alexherbo2/snippets.kak'

plug "jbomanson/search-doc.kak" config %{
        require-module search-doc
}

plug "andreyorst/smarttab.kak" defer smarttab %{
    # when `backspace' is pressed, 4 spaces are deleted at once
    set-option global softtabstop 4
} config %{
    # these languages will use `expandtab' behavior
    hook global WinSetOption filetype=.* expandtab
    # these languages will use `noexpandtab' behavior
    hook global WinSetOption filetype=(makefile|gas) noexpandtab
    # these languages will use `smarttab' behavior
    hook global WinSetOption filetype=(c|cpp|java) smarttab
}
plug "andreyorst/fzf.kak"

# Key Mappings

## jj to escape
hook global InsertChar j %{ try %{
  exec -draft hH <a-k>jj<ret> d
  exec <esc>
}}


## Mac Clipboard
hook global NormalKey y|d|c %{ nop %sh{
      printf %s "$kak_main_reg_dquote" | pbcopy
}}
map global user P -docstring 'Paste above' '!pbpaste<ret>'
map global user p -docstring 'Paste below' '<a-!>pbpaste<ret>'
map global user R -docstring 'Replace' '|pbpaste<ret>'

# general Configuration

##verbose autoinfo
set-option -add global autoinfo normal

## case insensitive search by default
map global normal / "/(?i)"

# Pandoc
set-option global pandoc_options "-d default"
 
# Appearance

colorscheme gruvbox

add-highlighter global/ number-lines -relative -hlcursor
add-highlighter global/ show-whitespaces

add-highlighter global/ line '%val{cursor_line}' default,rgb:3c3735
add-highlighter global/ column 81 default,red
add-highlighter global/ wrap -indent -word -marker ' … '
```

```
❯ which sh
/bin/sh
```

**Comment by jdugan6240** [comment] 2020-11-27 21:58
OK, thanks for the kakrc. I am able to reproduce the error with your config.

What is confusing me right now is that you seem to be using `plug.kak` to load the powerline.kak plugin. This is odd - that should be sufficient to bring in all the necessary modules for `powerline.kak`. I also don't think the `sh` executable is the issue, since I'm getting identical results to you without the fish shell installed.

This error message is emitted whenever the plugin rebuilds the status bar. This is done whenever the powerline separator is changed, whenever any module is toggled, whenever the powerline theme is changed, and whenever the powerline itself is enabled. I'm going to add various debug statements to determine at which points the git module isn't loaded.

**Comment by jdugan6240** [comment] 2020-11-27 22:19
OK, this issue may be the push I needed to rework how powerline.kak operates. There's a lot of unnecessary cruft that could potentially be simplified, so I'm just going to go ahead and work on that. This simplification should, as a byproduct, fix the issue of the git module not being loaded.

In the meantime, you could consider setting the `powerline_ignore_warnings` option to `true` to remove the warnings.

**Comment by jdugan6240** [comment] 2020-11-27 23:32
Sorry for the comment spam - this thread has basically become a brain dump at this point.

This is the strangest thing - the issue disappears when the line `printf "%s\n" "set-option global powerline_next_bg $bg"` is removed in git.kak. I have no idea what's going on anymore - this shouldn't be affecting anything, and the other modules don't have this issue.

I'm extremely tempted at this point to close this as a "wontfix", since the problem doesn't actually affect anything from a functionality standpoint, and only affects the debug buffer. Plus, there's a workaround with the `powerline_ignore_warnings` option.

**Comment by basbebe** [comment] 2020-11-28 07:46
Sounds understandable!

I had a problem though where I could've `got commit` within Kakoune because some hook couldn't execute.

I thought that powerline.kak could be the culprit but I wasn't able to reproduce it.

**Comment by jdugan6240** [comment] 2020-11-28 17:16
I can't imagine why `powerline.kak` would have any impact on the hooks Kakoune needs to execute any of the git commands. The only hooks Kakoune's git support uses are WinSetOption hooks for when the filetype of a buffer changes to git-related files, which `powerline.kak` doesn't touch.

In any case, I have one more idea on how I might go about fixing this issue, so I am going to give it one last shot today.

**Comment by jdugan6240** [comment] 2020-11-28 17:25
I think I might have cracked it. Run plug-update on your config to see if the problem is solved.

**Comment by basbebe** [comment] 2020-11-30 13:50
seems to be gone now, thanks!

**Closed** 2020-11-30 13:50 UTC
Labels: has_workaround
