### ISSUE TITLE
no theme loaded

### ISSUE THREAD

**Issue by basbebe** [jdugan6240/powerline.kak#9] opened 2021-02-04 20:55 UTC
## Problem description

Themes are not being loaded

## Steps to reproduce

1. use https://github.com/alexherbo2/plug.kak
2. use below `kakrc`
3. open kakoune

## What should happen

gruvbox theme loaded

## What happens instead

no theme loaded

If I switch the order, though:

```sh
    powerline-separator triangle
    powerline-start
    powerline-theme gruvbox
```

The correct theme gets loaded.
But then I get the bug `Warning, trying to load non-existing module 'git'` https://github.com/jdugan6240/powerline.kak/issues/8 again…

## Environment information
Kakoune version: 26cf5cd
OS version: macOS 11.2
`sh` executable version: fish, version 3.1.2

my totally messy `kakrc`:

```sh
require-module plug

# Let plug.kak manage itself.
plug plug https://github.com/alexherbo2/plug.kak %{
    # Upgrade plugins
    # Install plugins and build them.
    define-command plug-upgrade -docstring 'plug-upgrade' %{
        plug-install
        plug-execute connect make install
        plug-execute lsp cargo build --release
    }
}

plug-core %{
    # Tools
    set-option global makecmd 'make -j 8'
    set-option global grepcmd 'rg --column --with-filename'
}

plug-old pandoc git/pandoc.kak %{
    set-option global pandoc_options "-d default"
}

plug-old lsp https://github.com/kak-lsp/kak-lsp %{
    set global lsp_cmd "kak-lsp -s %val{session} --config ~/.config/kak-lsp/kak-lsp.toml"

    # uncomment to enable debugging
    # set global lsp_cmd "kak-lsp -s %val{session} --config ~/.config/kak-lsp/kak-lsp.toml -vvv --log /tmp/kak-lsp.log"
    # eval %sh{echo ${kak_opt_lsp_cmd} >> /tmp/kak-lsp.log}

    # this is not necessary; the `lsp-enable-window` will take care of it
    # eval %sh{${kak_opt_lsp_cmd} --kakoune -s $kak_session}

    set global lsp_diagnostic_line_error_sign '║'
    set global lsp_diagnostic_line_warning_sign '┊'

    define-command ne -docstring 'go to next error/warning from lsp' %{ lsp-find-error --include-warnings }
    define-command pe -docstring 'go to previous error/warning from lsp' %{ lsp-find-error --previous --include-warnings }
    define-command ee -docstring 'go to current error/warning from lsp' %{ lsp-find-error --include-warnings; lsp-find-error --previous --include-warnings }

    map global normal <#> ': enter-user-mode lsp<ret>' -docstring 'lsp'

    # Snippets
    # def -hidden insert-c-n %{
    #      try %{
    #             lsp-snippets-select-next-placeholders
    #                exec '<a-;>d'
    #      } catch %{
    #             exec -with-hooks '<c-n>'
    #      }
    # }
    # map global insert <c-n> "<a-;>: insert-c-n<ret>"

    define-command lsp-restart -docstring 'restart lsp server' %{ lsp-stop; lsp-start }
    hook global WinSetOption filetype=(c|cpp|cc|rust|python|java|latexi|markdown) %{
        set-option window lsp_auto_highlight_references true
        set-option window lsp_hover_anchor false
        lsp-auto-hover-enable
        echo -debug "Enabling LSP for filtetype %opt{filetype}"
        lsp-enable-window
    }

    hook global WinSetOption filetype=python %{
        set-option global lsp_server_configuration pyls.configurationSources=["flake8"]
    }

    hook global WinSetOption filetype=(rust) %{
        set window lsp_server_configuration rust.clippy_preference="on"
    }

    hook global WinSetOption filetype=rust %{
        hook window BufWritePre .* %{
            evaluate-commands %sh{
                test -f rustfmt.toml && printf lsp-formatting-sync
            }
        }
    }

    hook global KakEnd .* lsp-exit
}


plug fzf https://github.com/andreyorst/fzf.kak 
map global normal <c-p> ': fzf-mode<ret>'

plug-old kakoune-buffers https://github.com/delapouite/kakoune-buffers %{
    # Suggested hook

    hook global WinDisplay .* info-buffers

    # Suggested mappings

    map global user b ': enter-buffers-mode<ret>'              -docstring 'buffers…'
    map global user B ': enter-user-mode -lock buffers<ret>'   -docstring 'buffers (lock)…'
    map global user <a-b> ': pick-buffers<ret>' -docstring 'pick buffer…'

    # Suggested aliases

    alias global bd delete-buffer
    alias global bf buffer-first
    alias global bl buffer-last
    alias global bo buffer-only
    alias global bo! buffer-only-force
}

# plug kakoune-smooth-scroll https;//github.com/caksoylar/kakoune-smooth-scroll {
#     hook global WinCreate .* %{ hook -once window WinDisplay [^*].* smooth-scroll-enable }
# }

plug prelude https://github.com/alexherbo2/prelude.kak

plug connect https://github.com/alexherbo2/connect.kak %{
    # Modules
    require-module connect-fzf
    require-module connect-nnn
    require-module connect-broot

    hook global ModuleLoaded kitty %{
          alias global popup kitty-terminal-tab # or kitty-terminal
    }

    # compatibility
    # alias global repl-new kitty-repl

    # Create a new window

    # set-option global connect_environment %{
    #     export SHELL="/usr/local/bin/fish --init-command=\"set -x EDITOR :edit; set -x VISUAL :edit\""
    # }
}
map global normal <c-t> ': connect-terminal<ret>'

plug explore https://github.com/alexherbo2/explore.kak %{
    explore-enable

    alias global explore-files fzf-files
    alias global explore-buffers fzf-buffers
}

plug yank-ring https://github.com/alexherbo2/yank-ring.kak %{
    require-module yank-ring-connect

    yank-ring-enable

    map global normal Y ': yank-ring<ret>'
}

plug-old kakoune-sudo-write https://github.com/occivink/kakoune-sudo-write

plug-old number-toggle https://github.com/evanrelf/number-toggle.kak %{
    set-option global number_toggle_params -hlcursor
}

plug surround https://github.com/alexherbo2/surround.kak %{
    ## Quoting
    map -docstring 'Surround' global normal q ': enter-user-mode surround<ret>'
    map -docstring 'Surround insert' global normal Q ': surround-enter-insert-mode<ret>'
    map -docstring 'Surround (Replace)' global normal <a-q> ': surround-delete; enter-user-mode surround<ret>'

    ## Move macros to ^
    map -docstring 'Play macro' global normal ^ q
    map -docstring 'Record macro' global normal <a-^> Q
}

plug auto-pairs https://github.com/alexherbo2/auto-pairs.kak %{
    auto-pairs-enable
}

plug-old kakoune-show-matching-insert https://github.com/laelath/kakoune-show-matching-insert %{
    add-highlighter global/ ranges show_matching_insert
}

plug search-doc https://github.com/jbomanson/search-doc.kak %{
    alias global sd search-doc
}

plug smarttab https://github.com/andreyorst/smarttab.kak %{
    # when `backspace' is pressed, 4 spaces are deleted at once
    set-option global softtabstop 4

    # these languages will use `expandtab' behavior
    hook global WinSetOption filetype=.* expandtab
    # these languages will use `noexpandtab' behavior
    hook global WinSetOption filetype=(makefile|gas) noexpandtab
    # these languages will use `smarttab' behavior
    hook global WinSetOption filetype=(c|cpp) smarttab
}

plug palette https://github.com/alexherbo2/palette.kak

plug powerline https://github.com/jdugan6240/powerline.kak %{
    # set-option global powerline_format 'git bufname filetype mode_info line_column position'
    # powerline-toggle line_column off
    # source .config/kak/autoload/plugins/powerline/rc/themes/gruvbox.kak
    powerline-theme gruvbox
    powerline-separator triangle
    powerline-start
}

# Key Mappings

## Quit
map global normal <c-q> ': quit<ret>'

## quick safe
map global user w -docstring 'safe file' ': w<ret>'

## edit kakrc
map global user <,> -docstring 'edit kakrc' ': edit "%val{config}/kakrc"<ret>'
map global user <a-,> -docstring 'source kakrc' ': source "%val{config}/kakrc"<ret>'

## source current buffer
map global user <a-<> -docstring 'source current buffer' ': source "%val{buffile}<ret>'

## jj to escape
hook global InsertChar j %{ try %{
  exec -draft hH <a-k>jj<ret> d
  exec <esc>
}}

## alias for enter-user-mode
alias global u enter-user-mode

## commenting

map global user c -docstring '(un-)comment line' ': comment-line<ret>'
map global user C -docstring '(un-)comment block' ': comment-block<ret>'

## Mac Clipboard
hook global NormalKey y|d|c %{ nop %sh{
      printf %s "$kak_main_reg_dquote" | pbcopy
}}
map global user P -docstring 'Paste above' '!pbpaste<ret>'
map global user p -docstring 'Paste below' '<a-!>pbpaste<ret>'
map global user R -docstring 'Replace' '|pbpaste<ret>'


# IDE
# (needs connect.kak)

define-command ide -params 0..1 -docstring 'ide [session-name]: Turn Kakoune into an IDE' %{
  # Session name
  try %{
    rename-session %arg{1}
  }

  # Main client
  rename-client main
  set-option global jumpclient main

  # Tools client
  new %{
    rename-client tools
    set-option global toolsclient tools
  }

  # Docs client
  new %{
    rename-client docs
    set-option global docsclient docs
  }

  # Project drawer
  broot

  # Git
  > lazygit

  # Terminal
  >

  # get focus back
  focus main
}

# general Configuration

    ##verbose autoinfo
set-option -add global autoinfo normal

## case insensitive search by default
map global normal / "/(?i)"

# Appearance

colorscheme gruvbox

add-highlighter global/ number-lines -relative -hlcursor
add-highlighter global/ show-whitespaces

add-highlighter global/ line '%val{cursor_line}' default,rgb:3c3735
add-highlighter global/ column 81 default,red
add-highlighter global/ wrap -indent -word -marker ' … '
```

**Comment by jdugan6240** [comment] 2021-02-05 02:20
Since there's a lot in your config that could have been masking the issue, I took the liberty of distilling it down to the following:

```
require-module plug

# Let plug.kak manage itself.
plug plug https://github.com/alexherbo2/plug.kak %{
    # Upgrade plugins
    # Install plugins and build them.
    define-command plug-upgrade -docstring 'plug-upgrade' %{
        plug-install
    }
}

plug-core %{
    # Tools
    set-option global makecmd 'make -j 8'
    set-option global grepcmd 'rg --column --with-filename'
}

plug powerline https://github.com/jdugan6240/powerline.kak %{
    # set-option global powerline_format 'git bufname filetype mode_info line_column position'
    # powerline-toggle line_column off
    # source .config/kak/autoload/plugins/powerline/rc/themes/gruvbox.kak
    powerline-theme gruvbox
    powerline-separator triangle
    powerline-start
}

```

I am able to reproduce the issue with this config. It only seems to happen with alexherbo2's plug.kak, and not the original. This makes me think that something is off with how the modules are being loaded, since that is how the new plug.kak works. I'll do some testing tonight and see if I can't diagnose the problem.

**Comment by jdugan6240** [comment] 2021-02-05 02:50
OK, this is almost certainly an issue with the order in which the modules are loaded, since the necessary themes are loaded fine if I run powerline-enable beforehand. If that's the case, then unfortunately there's probably not a whole lot I can do about it. For now I'd recommend your fix that you found, starting the powerline before configuring it.

I'll keep looking into ways to play along with the new plug.kak better, though, since I'd like to eventually convert my own kakrc to it in the future.

**Comment by jdugan6240** [comment] 2021-02-05 03:01
I think I found something. I hate that we have to do it this way, but this gets rid of all the errors.

Try replacing the following in your kakrc:
```
plug powerline https://github.com/jdugan6240/powerline.kak %{
    # set-option global powerline_format 'git bufname filetype mode_info line_column position'
    # powerline-toggle line_column off
    # source .config/kak/autoload/plugins/powerline/rc/themes/gruvbox.kak
    powerline-theme gruvbox
    powerline-separator triangle
    powerline-start
}
```

with this:

```
plug powerline https://github.com/jdugan6240/powerline.kak

hook global -once WinDisplay .* %{
    powerline-enable
    #Now configure the powerline as desired...
    powerline-theme gruvbox
    powerline-separator triangle
}
```

In my case, this not only resolves the problem where the theme wasn't being loaded, it even gets rid of the git module error. If this works, I'll put a note in the README for using powerline.kak with the new plug.kak.

**Comment by basbebe** [comment] 2021-02-05 08:57
thanks for taking the time and for the workaround!

Maybe @alexherbo2 has an idea why this is?

**Comment by jdugan6240** [comment] 2021-02-05 19:46
I just found a problem with the workaround I gave you.

The problem is that modules that require hooks (like git and bufname) won't be able to register their hooks in time with this approach. It starts working when you change buffers, but that's obviously not ideal. To fix this, change to the following approach:

```
plug powerline https://github.com/jdugan6240/powerline.kak %{
    powerline-enable
}

hook global -once WinDisplay .* %{
    #Configure powerline.kak as desired
    powerline-theme gruvbox
    powerline-separator triangle
}
```

This enables powerline.kak whenever the module is loaded, and configures it afterwards. This is, incidentally, how the original plug.kak handled this plugin if you use the configuration in the README.

Personally, I don't think there's anything wrong with plug.kak - this plugin just has a fairly cumbersome modular design. If this approach resolves your problem, I'd like to add it to the README so we can close this issue.

**Comment by basbebe** [comment] 2021-02-05 20:52
although I wouldn/t say that I like it aesthetically 😜, it mostly works now, thanks!

What I\m missing now though is the current git tree. That won't show…

**Comment by basbebe** [comment] 2021-02-05 22:16
but now the theme gets lost when I load a new buffer.

**Comment by jdugan6240** [comment] 2021-02-06 01:57
OK, first off, no - you no stupid. Everyone makes mistakes like that every once in a while. I've made quite a few today at work.

Second, why is the theme getting lost? I hate to be that guy, but it works on my machine.

Can you post your updated kakrc?

**Comment by basbebe** [comment] 2021-02-06 06:52
I was wrong: It doesn't lose the theme but the separator setting when I open another file.

My completely refactored kakrc (took the liberty to use some one elses tidier one and merged):

https://github.com/basbebe/.dotfiles/blob/master/.config/kak/kakrc

```sh
# Preamble
require-module plug

# Let plug.kak manage itself.
plug plug https://github.com/alexherbo2/plug.kak %{
  # Upgrade plugins
  # Install plugins and build them.
  define-command plug-upgrade -docstring 'plug-upgrade' %{
    plug-install
    plug-execute connect make install
    plug-execute lsp cargo build --release --locked
  }
}

plug-core %{
  # Options ────────────────────────────────────────────────────────────────────

  # User interface
  set-option -add global ui_options ncurses_status_on_top=yes
  set-option -add global ui_options ncurses_assistant=cat
  set-option -add global ui_options ncurses_set_title=no

  # Color scheme
  # Gruvbox theme for Kakoune
  # https://github.com/morhetz/gruvbox
  colorscheme gruvbox

  # Status line
  #
  # Display Unicode code point in the status line.
  #
  # https://en.wikipedia.org/wiki/Unicode
  # https://en.wikipedia.org/wiki/Code_point
  # set-option global modelinefmt '{yellow}%opt{out_of_view_status_line}{default} {{mode_info}} {magenta}%val{client}{default} at {yellow}%val{session}{default} on {green}%val{bufname}{default} {{context_info}} {cyan}U+%sh{printf ''%04x'' "$kak_cursor_char_value"}{default} {cyan}%val{cursor_line}{default}:{cyan}%val{cursor_char_column}{default}'

  # Verbose Autoinfo
  set-option -add global autoinfo normal

  # Highlighters
  add-highlighter global/ number-lines -relative -hlcursor
  add-highlighter global/show-matching show-matching
  add-highlighter global/show-whitespaces show-whitespaces
  add-highlighter global/ line '%val{cursor_line}' default,rgb:3c3735
  add-highlighter global/ column 81 default,rgb:3c3836
  add-highlighter global/ wrap -indent -word

  # Scroll offset
  set-option global scrolloff 5,1

  # Indentation
  # Indent with 2 spaces and make tabs appear as 2 spaces.
  set-option global tabstop 2
  set-option global indentwidth 2

  # Filetype-specific
  # Makefile
  hook global WinSetOption filetype=makefile %{
    set-option window indentwidth 0
  }

  # Python
  hook global WinSetOption filetype=python %{
    set-option window tabstop 4
    set-option window indentwidth 4
  }

  # Windowing
  hook global ModuleLoaded kitty %{
    alias global terminal kitty-terminal
    alias global popup kitty-terminal # or kitty-terminal-tab
  }

  # Tools
  set-option global makecmd 'make -j 8'
  set-option global grepcmd 'rg --column --with-filename'

  # Commands ───────────────────────────────────────────────────────────────────


  # IDE
  # (needs connect.kak)

  define-command ide -params 0..1 -docstring 'ide [session-name]: Turn Kakoune into an IDE' %{
    # Session name
    try %{
      rename-session %arg{1}
    }

    # Main client
    rename-client main
    set-option global jumpclient main

    # Tools client
    new %{
      rename-client tools
      set-option global toolsclient tools
    }

    # Docs client
    new %{
      rename-client docs
      set-option global docsclient docs
    }

    # Project drawer
    broot

    # Git
    > lazygit

    # Terminal
    >

    # get focus back
    focus main
  }

  # lazygit
  # https://github.com/jesseduffield/lazygit
  define-command lazygit -params .. -docstring 'Open lazygit' %{
    + lazygit %arg{@}
  }

  alias global lg lazygit

  # Aliases ────────────────────────────────────────────────────────────────────

  # User modes
  alias global u enter-user-mode


  # Quick editing
  define-command -docstring 'Open kakrc' edit-kakoune 'edit ~/.config/kak/kakrc'
  define-command -docstring 'Open tmux.conf' edit-tmux 'edit ~/.tmux.conf'
  define-command -docstring 'Open kitty.conf' edit-kitty 'edit ~/.config/kitty/kitty.conf'
  define-command -docstring 'Open config.fish' edit-fish 'edit ~/.config/fish/config.fish'
  define-command -docstring 'Open gitconfig' edit-git 'edit ~/.gitconfig'
  define-command -docstring 'Open broot/conf.toml' edit-broot 'edit ~/.config/broot/conf.hjson'
  define-command -docstring 'Open starship.toml' edit-starship 'edit ~/.config/starship.toml'

  # Aliases
  alias global ek edit-kakoune

  # Git
  alias global G lazygit

  # dotfiles
  define-command -docstring 'open dotfiles with lazygit' dotfiles '> fish -c dotfiles'

  # Mappings ───────────────────────────────────────────────────────────────────

  # Big keys
  # [Enter] [Backspace] [Tab] [Alt-Tab]
  map -docstring 'Enter command prompt' global normal <ret> :
  map -docstring 'Reduce selections to their cursor' global normal <backspace> ';'
  map -docstring 'Swap selections cursor and anchor' global normal <tab> '<a-;>'
  map -docstring 'Ensure selection cursor is after anchor' global normal <a-tab> '<a-:>'

  # Keep the jump functionality on Enter for grep and make.
  hook global WinSetOption filetype=grep %{
    map -docstring 'grep-jump' window normal <ret> ': grep-jump<ret>'
  }

  hook global WinSetOption filetype=make %{
    map -docstring 'make-jump' window normal <ret> ': make-jump<ret>'
  }

  # Control keys
  # [C-a] [C-f] [C-n] [C-o] [C-q] [C-s] [C-t] [C-w] [C-x]
  map -docstring 'Alternate buffer' global normal <c-a> ga
  map -docstring 'Find in buffer' global normal <c-f> '/(?i)\Q'
  map -docstring 'Find in buffer' global prompt <c-f> '<home>(?i)\Q<end>'
  map -docstring 'Open a new terminal window' global normal <c-n> ': connect-terminal<ret>'
  map -docstring 'Open file' global normal <c-o> ':edit<space>'
  map -docstring 'Quit' global normal <c-q> ': quit<ret>'
  map -docstring 'Save buffer' global normal <c-s> ': write<ret>'
  map -docstring 'Open a new tab' global normal <c-t> ': new<ret>'
  map -docstring 'Terminal' global normal <c-w> ': enter-user-mode terminal<ret>'
  map -docstring 'Write and quit' global normal <c-x> ': write-quit<ret>'

  # case insensitive search by default
  map global normal / "/(?i)"

  # Paths
  map -docstring 'Current buffer name' global prompt <a-?> '<c-r>%'
  map -docstring 'Current buffer directory' global prompt <a-/> '%sh(dirname "$kak_bufname")<a-!>/'

  # Select all occurrences of the current selection set.
  map -docstring 'Select all occurrences of the current selection set' global normal <a-percent> '*%s<ret>'

  # edit kakrc
  map -docstring 'Open kakrc' global user <,> ': edit-kakoune<ret>'

  # commenting
  map global user c -docstring '(un-)comment line' ': comment-line<ret>'
  map global user C -docstring '(un-)comment block' ': comment-block<ret>'

  # Mac Clipboard
  hook global NormalKey y|d|c %{
    nop %sh{
      printf %s "$kak_main_reg_dquote" | pbcopy
    }
  }

  map global user P -docstring 'Paste above' '!pbpaste<ret>'
  map global user p -docstring 'Paste below' '<a-!>pbpaste<ret>'
  map global user R -docstring 'Replace' '|pbpaste<ret>'

  # Move macros to ^
  map -docstring 'Play macro' global normal ^ q
  map -docstring 'Record macro' global normal <a-^> Q

}

# Plugins ──────────────────────────────────────────────────────────────────────

plug auto-pairs https://github.com/alexherbo2/auto-pairs.kak %{
    auto-pairs-enable
}

plug edit https://github.com/alexherbo2/edit.kak

plug capitalize-selections https://github.com/alexherbo2/capitalize-selections.kak %{
  map -docstring 'Capitalize selections' global normal <a-`> ': capitalize-selections<ret>'
}

plug connect https://github.com/alexherbo2/connect.kak %{
  # Modules
  require-module connect-fzf
  require-module connect-nnn
  require-module connect-broot

  set-option global connect_environment %{
    # export SHELL="/usr/local/bin/fish --init-command=\"set -x EDITOR :edit; set -x VISUAL :edit\""
  }
}

plug current-word-highlighter https://github.com/alexherbo2/current-word-highlighter.kak %{
    current-word-highlighter-enable
}


plug double-tap https://github.com/alexherbo2/double-tap.kak %{
  # Type "jj" to leave insert mode:
  double-tap-escape global j
}

plug execute-key https://github.com/alexherbo2/execute-key.kak

plug explore https://github.com/alexherbo2/explore.kak %{
  explore-enable

  # Configure the file explorer
  alias global explore-files fzf-files
  alias global explore-buffers fzf-buffers
}

plug-old find https://github.com/occivink/kakoune-find

plug jq https://github.com/alexherbo2/jq.kak %{
  map -docstring 'jq' global user | ': jq-prompt<ret>'
  map -docstring 'jq-selections' global user <a-|> ': jq-prompt-selections<ret>'
}

plug-old kakoune-buffers https://github.com/delapouite/kakoune-buffers %{
  # Suggested hook

  hook global WinDisplay .* info-buffers

  # Suggested mappings

  map global user b ': enter-buffers-mode<ret>' -docstring 'buffers…'
  map global user B ': enter-user-mode -lock buffers<ret>' -docstring 'buffers (lock)…'
  map global user <a-b> ': pick-buffers<ret>' -docstring 'pick buffer…'

  # Suggested aliases

  alias global bd delete-buffer
  alias global bf buffer-first
  alias global bl buffer-last
  alias global bo buffer-only
  alias global bo! buffer-only-force
}

nop plug-old smooth-scroll https://github.com/caksoylar/kakoune-smooth-scroll %{
     hook global WinCreate .* %{ hook -once window WinDisplay [^*].* smooth-scroll-enable }
 }

plug-old lsp https://github.com/kak-lsp/kak-lsp %{
  set global lsp_cmd "kak-lsp -s %val{session} --config ~/.config/kak-lsp/kak-lsp.toml"

  # uncomment to enable debugging
  # set global lsp_cmd "kak-lsp -s %val{session} --config ~/.config/kak-lsp/kak-lsp.toml -vvv --log /tmp/kak-lsp.log"
  # eval %sh{echo ${kak_opt_lsp_cmd} >> /tmp/kak-lsp.log}

  # this is not necessary; the `lsp-enable-window` will take care of it
  # eval %sh{${kak_opt_lsp_cmd} --kakoune -s $kak_session}

  set global lsp_diagnostic_line_error_sign '║'
  set global lsp_diagnostic_line_warning_sign '┊'

  define-command ne -docstring 'go to next error/warning from lsp' %{ lsp-find-error --include-warnings }
  define-command pe -docstring 'go to previous error/warning from lsp' %{ lsp-find-error --previous --include-warnings }
  define-command ee -docstring 'go to current error/warning from lsp' %{ lsp-find-error --include-warnings; lsp-find-error --previous --include-warnings }

  map global normal <#> ': enter-user-mode lsp<ret>' -docstring 'lsp'

  # Snippets
  # def -hidden insert-c-n %{
  #      try %{
  #             lsp-snippets-select-next-placeholders
  #                exec '<a-;>d'
  #      } catch %{
  #             exec -with-hooks '<c-n>'
  #      }
  # }
  # map global insert <c-n> "<a-;>: insert-c-n<ret>"

  define-command lsp-restart -docstring 'restart lsp server' %{ lsp-stop; lsp-start }
  hook global WinSetOption filetype=(c|cpp|cc|rust|python|java|latexi|markdown) %{
    set-option window lsp_auto_highlight_references true
    set-option window lsp_hover_anchor false
    lsp-auto-hover-enable
    echo -debug "Enabling LSP for filtetype %opt{filetype}"
    lsp-enable-window
  }

  hook global WinSetOption filetype=python %{
  #   set-option global lsp_server_configuration pyls.configurationSources=["flake8"]
  }

  hook global KakEnd .* lsp-exit
}

plug move-line https://github.com/alexherbo2/move-line.kak %{
  map -docstring 'Move selected lines below' global normal <down> ': move-line-below<ret>'
  map -docstring 'Move selected lines above' global normal <up> ': move-line-above<ret>'
}

plug-old number-toggle https://github.com/evanrelf/number-toggle.kak %{
    set-option global number_toggle_params -hlcursor
}

plug palette https://github.com/alexherbo2/palette.kak %{
  palette-enable
}

plug objectify https://github.com/alexherbo2/objectify.kak

plug out-of-view https://github.com/alexherbo2/out-of-view.kak %{
  out-of-view-enable
}

plug-old pandoc git/pandoc.kak %{
  set-option global pandoc_options "-d default"
}

plug powerline https://github.com/jdugan6240/powerline.kak %{
  powerline-enable
}
hook global -once WinDisplay .* %{
  #Configure powerline.kak as desired
  # set-option global powerline_format 'git bufname filetype mode_info line_column position'
  set-option global powerline_format 'git lsp bufname mode_info line_column client session filetype smarttab position'
  set-option global powerline_shorten_bufname 'short'
  set-option global powerline_position_minimap_format true
  powerline-theme gruvbox
  powerline-separator none
}

plug prelude https://github.com/alexherbo2/prelude.kak

plug replace-mode https://github.com/alexherbo2/replace-mode.kak %{
  map -docstring 'Replace' global user r ': enter-replace-mode<ret>'
}

plug-old kakoune-show-matching-insert https://github.com/laelath/kakoune-show-matching-insert %{
    add-highlighter global/ ranges show_matching_insert
}

plug search-doc https://github.com/jbomanson/search-doc.kak %{
    alias global sd search-doc
}

plug search-highlighter https://github.com/alexherbo2/search-highlighter.kak %{
  search-highlighter-enable
}

plug sleuth https://github.com/alexherbo2/sleuth.kak %{
  sleuth-enable
}

plug smarttab https://github.com/andreyorst/smarttab.kak %{
    # when `backspace' is pressed, 2 spaces are deleted at once
    set-option global softtabstop 2

    # these languages will use `expandtab' behavior
    hook global WinSetOption filetype=.* expandtab
    # these languages will use `noexpandtab' behavior
    hook global WinSetOption filetype=(makefile|gas) noexpandtab
    # these languages will use `smarttab' behavior
    hook global WinSetOption filetype=(c|cpp) smarttab
}

plug-old sudo-write https://github.com/occivink/kakoune-sudo-write

plug surround https://github.com/alexherbo2/surround.kak %{
    ## Quoting
    map -docstring 'Surround' global normal q ': enter-user-mode surround<ret>'
    map -docstring 'Surround insert' global normal Q ': surround-enter-insert-mode<ret>'
    # map -docstring 'Surround (Replace)' global normal <a-q> ': surround-delete; enter-user-mode surround<ret>'
}

plug terminal-mode https://github.com/alexherbo2/terminal-mode.kak

plug text-objects https://github.com/alexherbo2/text-objects.kak

plug-old vertical-selection https://github.com/occivink/kakoune-vertical-selection

plug volatile-highlighter https://github.com/alexherbo2/volatile-highlighter.kak %{
  volatile-highlighter-enable
}

plug yank-ring https://github.com/alexherbo2/yank-ring.kak %{
  # Modules
  require-module yank-ring-connect

  # Enable yank-ring
  yank-ring-enable
 map global normal Y ': yank-ring<ret>'
}
```

**Comment by jdugan6240** [comment] 2021-02-06 08:25
Ah, so that's what you're referring to. Yes, this is how the `powerline-separator` command works. As weird as it may seem, this is intended behavior - it allows the user to have different separators per buffer.

If you want to discuss this further, let's open a separate issue for it, since it is unrelated to plug.kak. I agree that there should be a way to set separators globally, but I don't want to bloat this thread more than it already is. I'm not going to open the issue right now, though, since frankly I'm currently up way later than I should be 😋.

**Comment by jdugan6240** [comment] 2021-02-06 17:31
OK, a new issue has been opened regarding the `powerline-separator` issue.

Since the workaround I gave you appears to solve the original problem you had, I'm going to add it to the README and close this issue. Feel free to reopen if you're still having problems.

**Closed** 2021-02-06 17:32 UTC
Labels: has_workaround
